[[exchange]]
id = "blockfi"
name = "BlockFI"
url = "https://www.blockfi.com"

[[exchange.pair]]
pair = ["btc", "USD"]

[[exchange.pair]]
pair = ["ltc", "USD"]

[[exchange.pair]]
pair = ["eth", "USD"]
