[[price]]
pair = ["btc", "USD"]
value = 49304.0

[[price]]
pair = ["eth", "USD"]
value = 2211.61

[[price]]
pair = ["xrp", "USD"]
value = 1.04

[[price]]
pair = ["ada", "USD"]
value = 1.05

[[price]]
pair = ["dot", "USD"]
value = 29.3

[[price]]
pair = ["uni", "USD"]
value = 31.69

[[price]]
pair = ["ltc", "USD"]
value = 226.77

[[price]]
pair = ["link", "USD"]
value = 32.28

[[price]]
pair = ["sol", "USD"]
value = 33.85

[[price]]
pair = ["xlm", "USD"]
value = 0.398461

[[price]]
pair = ["xmr", "USD"]
value = 317.33

[[price]]
pair = ["eos", "USD"]
value = 5.07

[[price]]
pair = ["miota", "USD"]
value = 1.72

[[price]]
pair = ["atom", "USD"]
value = 17.19

[[price]]
pair = ["aave", "USD"]
value = 330.61

[[price]]
pair = ["dai", "USD"]
value = 1.0

[[price]]
pair = ["algo", "USD"]
value = 1.05

[[price]]
pair = ["AVAX", "USD"]
value = 21.2

[[price]]
pair = ["ksm", "USD"]
value = 301.07

[[price]]
pair = ["comp", "USD"]
value = 476.6

[[price]]
pair = ["zec", "USD"]
value = 193.71

[[price]]
pair = ["sushi", "USD"]
value = 10.86

[[price]]
pair = ["grt", "USD"]
value = 1.26

[[price]]
pair = ["bat", "USD"]
value = 0.978398

[[price]]
pair = ["uma", "USD"]
value = 22.27

[[price]]
pair = ["icx", "USD"]
value = 1.64

[[price]]
pair = ["nano", "USD"]
value = 6.79

[[price]]
pair = ["one", "USD"]
value = 0.093549

[[price]]
pair = ["xsushi", "USD"]
value = 12.38

[[price]]
pair = ["celo", "USD"]
value = 4.53

[[price]]
pair = ["ocean", "USD"]
value = 1.03

[[price]]
pair = ["trac", "USD"]
value = 0.513607

[[price]]
pair = ["pols", "USD"]
value = 2.35

[[price]]
pair = ["dag", "USD"]
value = 0.06329

[[price]]
pair = ["sylo", "USD"]
value = 0.0078187
