[[price]]
pair = ["btc", "USD"]
value = 50481.0

[[price]]
pair = ["eth", "USD"]
value = 2312.89

[[price]]
pair = ["xrp", "USD"]
value = 1.14

[[price]]
pair = ["usdt", "USD"]
value = 1.0

[[price]]
pair = ["ada", "USD"]
value = 1.17

[[price]]
pair = ["dot", "USD"]
value = 32.26

[[price]]
pair = ["uni", "USD"]
value = 32.56

[[price]]
pair = ["ltc", "USD"]
value = 234.95

[[price]]
pair = ["link", "USD"]
value = 34.08

[[price]]
pair = ["usdc", "USD"]
value = 0.999975

[[price]]
pair = ["xlm", "USD"]
value = 0.443548

[[price]]
pair = ["sol", "USD"]
value = 36.79

[[price]]
pair = ["xmr", "USD"]
value = 368.54

[[price]]
pair = ["eos", "USD"]
value = 5.45

[[price]]
pair = ["miota", "USD"]
value = 1.82

[[price]]
pair = ["atom", "USD"]
value = 19.88

[[price]]
pair = ["aave", "USD"]
value = 342.44

[[price]]
pair = ["dai", "USD"]
value = 0.999477

[[price]]
pair = ["algo", "USD"]
value = 1.16

[[price]]
pair = ["AVAX", "USD"]
value = 23.7

[[price]]
pair = ["comp", "USD"]
value = 590.22

[[price]]
pair = ["ksm", "USD"]
value = 329.96

[[price]]
pair = ["zec", "USD"]
value = 214.04

[[price]]
pair = ["sushi", "USD"]
value = 11.51

[[price]]
pair = ["bat", "USD"]
value = 1.14

[[price]]
pair = ["grt", "USD"]
value = 1.38

[[price]]
pair = ["uma", "USD"]
value = 23.17

[[price]]
pair = ["icx", "USD"]
value = 1.86

[[price]]
pair = ["nano", "USD"]
value = 8.18

[[price]]
pair = ["one", "USD"]
value = 0.107464

[[price]]
pair = ["xsushi", "USD"]
value = 13.12

[[price]]
pair = ["celo", "USD"]
value = 5.58

[[price]]
pair = ["ocean", "USD"]
value = 1.12

[[price]]
pair = ["reef", "USD"]
value = 0.03362896

[[price]]
pair = ["trac", "USD"]
value = 0.541983

[[price]]
pair = ["dag", "USD"]
value = 0.067736

[[price]]
pair = ["pols", "USD"]
value = 2.43

[[price]]
pair = ["powr", "USD"]
value = 0.34039

[[price]]
pair = ["sylo", "USD"]
value = 0.00837433

[[price]]
pair = ["gs", "USD"]
value = 0.953331
