coins = [
  "btc",
  "eth",
  "dot",
  "atom",
  "xlm",
  "ada",
  "ltc",
  "algo",
  "celo",
  "xmr",
  "miota",
  "eos",
  "ksm",
  "nano",
  ["comp", "compound-governance-token"],
  "link",
  "zec",
  "aave",
  "ocean",
  "bat",
  "xrp",
  ["grt", "the-graph"],
  "sushi",
  "AVAX",
  ["one", "harmony"],
  "icx",
  "sol",
  ["uni", "uniswap"],
  "dai",
  "sylo",
  "pols",
  "xsushi",
  "dag",
  "trac",
  "uma"
]
