CREATE TABLE IF NOT EXISTS prices (
  base VARCHAR  NOT NULL,
  target VARCHAR  NOT NULL,
  ts TIMESTAMP NOT NULL,
  value DOUBLE PRECISION NOT NULL,
  PRIMARY KEY (base, target, ts),
  FOREIGN KEY (base) REFERENCES assets (id) ON DELETE CASCADE,
  FOREIGN KEY (target) REFERENCES assets (id) ON DELETE CASCADE
);
