CREATE TABLE IF NOT EXISTS identities (
  id SERIAL NOT NULL PRIMARY KEY,
  name VARCHAR NOT NULL,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS sessions (
  id SERIAL NOT NULL PRIMARY KEY,
  identity SERIAL NOT NULL,
  expires TIMESTAMP,
  FOREIGN KEY (identity) REFERENCES identities (id) ON DELETE CASCADE
);
