last_updated = "2021-05-05T01:23:42.417864746Z"

[[price]]
pair = ["btc", "USD"]
value = 55128.0
market_cap = 1034090916014.0
price_change_percentage_24h = -0.87203
market_cap_change_percentage_24h = -0.60424

[[price]]
pair = ["eth", "USD"]
value = 3393.54
market_cap = 391972771439.0
price_change_percentage_24h = 2.06418
market_cap_change_percentage_24h = 2.29423

[[price]]
pair = ["xrp", "USD"]
value = 1.47
market_cap = 67826971030.0
price_change_percentage_24h = -0.215
market_cap_change_percentage_24h = 0.63599

[[price]]
pair = ["usdt", "USD"]
value = 1.0
market_cap = 53266673817.0
price_change_percentage_24h = 0.3139
market_cap_change_percentage_24h = 2.00139

[[price]]
pair = ["ada", "USD"]
value = 1.32
market_cap = 42251461492.0
price_change_percentage_24h = 0.59019
market_cap_change_percentage_24h = 0.69676

[[price]]
pair = ["dot", "USD"]
value = 36.53
market_cap = 36236636414.0
price_change_percentage_24h = 1.38904
market_cap_change_percentage_24h = 1.90848

[[price]]
pair = ["uni", "USD"]
value = 43.23
market_cap = 22656633460.0
price_change_percentage_24h = 5.21986
market_cap_change_percentage_24h = 6.31239

[[price]]
pair = ["ltc", "USD"]
value = 338.83
market_cap = 22582265335.0
price_change_percentage_24h = 20.05976
market_cap_change_percentage_24h = 20.57752

[[price]]
pair = ["link", "USD"]
value = 49.56
market_cap = 20955215619.0
price_change_percentage_24h = 23.08737
market_cap_change_percentage_24h = 23.80283

[[price]]
pair = ["usdc", "USD"]
value = 1.0
market_cap = 14985288400.0
price_change_percentage_24h = -0.16809
market_cap_change_percentage_24h = 1.60452

[[price]]
pair = ["vet", "USD"]
value = 0.198768
market_cap = 12735630181.0
price_change_percentage_24h = -2.64375
market_cap_change_percentage_24h = -3.61175

[[price]]
pair = ["sol", "USD"]
value = 45.02
market_cap = 12285566177.0
price_change_percentage_24h = 1.09529
market_cap_change_percentage_24h = 1.58492

[[price]]
pair = ["xlm", "USD"]
value = 0.52635
market_cap = 12094429312.0
price_change_percentage_24h = -0.52965
market_cap_change_percentage_24h = -0.36167

[[price]]
pair = ["theta", "USD"]
value = 10.77
market_cap = 10777518493.0
price_change_percentage_24h = -2.48242
market_cap_change_percentage_24h = -1.99851

[[price]]
pair = ["neo", "USD"]
value = 103.5
market_cap = 7292182761.0
price_change_percentage_24h = 1.21477
market_cap_change_percentage_24h = 2.30978

[[price]]
pair = ["xmr", "USD"]
value = 400.03
market_cap = 7147763021.0
price_change_percentage_24h = 0.5257
market_cap_change_percentage_24h = 0.73493

[[price]]
pair = ["eos", "USD"]
value = 7.11
market_cap = 6786939475.0
price_change_percentage_24h = 9.63119
market_cap_change_percentage_24h = 10.03496

[[price]]
pair = ["aave", "USD"]
value = 473.16
market_cap = 6011912111.0
price_change_percentage_24h = -3.54404
market_cap_change_percentage_24h = -3.15628

[[price]]
pair = ["miota", "USD"]
value = 1.96
market_cap = 5432835416.0
price_change_percentage_24h = -0.29466
market_cap_change_percentage_24h = 0.10154

[[price]]
pair = ["atom", "USD"]
value = 21.94
market_cap = 5238338092.0
price_change_percentage_24h = -0.44414
market_cap_change_percentage_24h = -0.08778

[[price]]
pair = ["AVAX", "USD"]
value = 32.37
market_cap = 4160457573.0
price_change_percentage_24h = -3.9343
market_cap_change_percentage_24h = -3.67893

[[price]]
pair = ["algo", "USD"]
value = 1.34
market_cap = 3986156209.0
price_change_percentage_24h = -2.58795
market_cap_change_percentage_24h = -1.12745

[[price]]
pair = ["dai", "USD"]
value = 1.0
market_cap = 3967607140.0
price_change_percentage_24h = 0.05525
market_cap_change_percentage_24h = 1.43619

[[price]]
pair = ["comp", "USD"]
value = 763.54
market_cap = 3889849009.0
price_change_percentage_24h = -5.76663
market_cap_change_percentage_24h = -5.38908

[[price]]
pair = ["ksm", "USD"]
value = 408.25
market_cap = 3672808367.0
price_change_percentage_24h = -0.16031
market_cap_change_percentage_24h = 0.44151

[[price]]
pair = ["zec", "USD"]
value = 257.43
market_cap = 2861223857.0
price_change_percentage_24h = 8.53923
market_cap_change_percentage_24h = 9.32005

[[price]]
pair = ["sushi", "USD"]
value = 13.39
market_cap = 2230624565.0
price_change_percentage_24h = -3.36702
market_cap_change_percentage_24h = -2.91509

[[price]]
pair = ["grt", "USD"]
value = 1.51
market_cap = 1854688257.0
price_change_percentage_24h = -1.60146
market_cap_change_percentage_24h = -1.17465

[[price]]
pair = ["bat", "USD"]
value = 1.22
market_cap = 1819920713.0
price_change_percentage_24h = -0.92535
market_cap_change_percentage_24h = -1.02873

[[price]]
pair = ["uma", "USD"]
value = 24.97
market_cap = 1508526583.0
price_change_percentage_24h = -1.31133
market_cap_change_percentage_24h = -0.65227

[[price]]
pair = ["icx", "USD"]
value = 2.26
market_cap = 1402565186.0
price_change_percentage_24h = -3.76272
market_cap_change_percentage_24h = -2.68235

[[price]]
pair = ["one", "USD"]
value = 0.131116
market_cap = 1248724808.0
price_change_percentage_24h = -2.93709
market_cap_change_percentage_24h = -0.20395

[[price]]
pair = ["nano", "USD"]
value = 9.15
market_cap = 1218658854.0
price_change_percentage_24h = -3.95163
market_cap_change_percentage_24h = -3.1844

[[price]]
pair = ["xsushi", "USD"]
value = 15.08
market_cap = 790213908.0
price_change_percentage_24h = -11.43443
market_cap_change_percentage_24h = -4.30157

[[price]]
pair = ["ocean", "USD"]
value = 1.34
market_cap = 572444562.0
price_change_percentage_24h = -2.52568
market_cap_change_percentage_24h = -2.1446

[[price]]
pair = ["celo", "USD"]
value = 5.09
market_cap = 562240226.0
price_change_percentage_24h = -4.56031
market_cap_change_percentage_24h = -3.80685

[[price]]
pair = ["reef", "USD"]
value = 0.03853612
market_cap = 488479657.0
price_change_percentage_24h = -0.0584
market_cap_change_percentage_24h = 0.04364

[[price]]
pair = ["ewt", "USD"]
value = 14.25
market_cap = 476706409.0
price_change_percentage_24h = -7.17811
market_cap_change_percentage_24h = -6.87868

[[price]]
pair = ["nmr", "USD"]
value = 67.41
market_cap = 383371634.0
price_change_percentage_24h = -2.23535
market_cap_change_percentage_24h = -1.11965

[[price]]
pair = ["trac", "USD"]
value = 0.64832
market_cap = 234483228.0
price_change_percentage_24h = -7.97477
market_cap_change_percentage_24h = -7.47542

[[price]]
pair = ["pols", "USD"]
value = 3.49
market_cap = 232406163.0
price_change_percentage_24h = -4.51764
market_cap_change_percentage_24h = -4.22346

[[price]]
pair = ["dag", "USD"]
value = 0.073979
market_cap = 175616827.0
price_change_percentage_24h = -1.0203
market_cap_change_percentage_24h = -0.12942

[[price]]
pair = ["nu", "USD"]
value = 0.47636
market_cap = 166909220.0
price_change_percentage_24h = -4.08693
market_cap_change_percentage_24h = -2.98468

[[price]]
pair = ["powr", "USD"]
value = 0.373386
market_cap = 160604879.0
price_change_percentage_24h = -5.23564
market_cap_change_percentage_24h = -4.97614

[[price]]
pair = ["sylo", "USD"]
value = 0.00826808
market_cap = 21412880.0
price_change_percentage_24h = 7.45268
market_cap_change_percentage_24h = 8.67295

[[price]]
pair = ["gs", "USD"]
value = 1.8
market_cap = 0.0
price_change_percentage_24h = -11.38022
market_cap_change_percentage_24h = 0.0
