last_updated = "2021-04-24T17:38:10.700262858Z"

[[price]]
pair = ["btc", "USD"]
value = 49906.0

[[price]]
pair = ["eth", "USD"]
value = 2232.52

[[price]]
pair = ["usdt", "USD"]
value = 1.0

[[price]]
pair = ["xrp", "USD"]
value = 1.06

[[price]]
pair = ["ada", "USD"]
value = 1.11

[[price]]
pair = ["dot", "USD"]
value = 29.23

[[price]]
pair = ["uni", "USD"]
value = 30.41

[[price]]
pair = ["ltc", "USD"]
value = 225.41

[[price]]
pair = ["usdc", "USD"]
value = 0.999047

[[price]]
pair = ["link", "USD"]
value = 31.66

[[price]]
pair = ["sol", "USD"]
value = 39.17

[[price]]
pair = ["xlm", "USD"]
value = 0.423432

[[price]]
pair = ["xmr", "USD"]
value = 370.17

[[price]]
pair = ["eos", "USD"]
value = 5.16

[[price]]
pair = ["miota", "USD"]
value = 1.68

[[price]]
pair = ["atom", "USD"]
value = 18.64

[[price]]
pair = ["aave", "USD"]
value = 321.18

[[price]]
pair = ["dai", "USD"]
value = 1.0

[[price]]
pair = ["algo", "USD"]
value = 1.1

[[price]]
pair = ["AVAX", "USD"]
value = 22.06

[[price]]
pair = ["comp", "USD"]
value = 550.72

[[price]]
pair = ["ksm", "USD"]
value = 300.39

[[price]]
pair = ["zec", "USD"]
value = 200.29

[[price]]
pair = ["sushi", "USD"]
value = 10.82

[[price]]
pair = ["bat", "USD"]
value = 1.05

[[price]]
pair = ["grt", "USD"]
value = 1.27

[[price]]
pair = ["uma", "USD"]
value = 21.18

[[price]]
pair = ["icx", "USD"]
value = 1.67

[[price]]
pair = ["nano", "USD"]
value = 7.44

[[price]]
pair = ["one", "USD"]
value = 0.097126

[[price]]
pair = ["xsushi", "USD"]
value = 12.31

[[price]]
pair = ["celo", "USD"]
value = 5.48

[[price]]
pair = ["ocean", "USD"]
value = 1.04

[[price]]
pair = ["reef", "USD"]
value = 0.03101303

[[price]]
pair = ["trac", "USD"]
value = 0.503861

[[price]]
pair = ["dag", "USD"]
value = 0.068343

[[price]]
pair = ["pols", "USD"]
value = 2.49

[[price]]
pair = ["powr", "USD"]
value = 0.328726

[[price]]
pair = ["sylo", "USD"]
value = 0.00844108

[[price]]
pair = ["gs", "USD"]
value = 0.866505
