last_updated = "2021-05-13T00:30:44.787155846Z"

[[price]]
pair = ["btc", "USD"]
value = 49406.0
market_cap = 907885014890.0
price_change_percentage_24h = -13.32495
market_cap_change_percentage_24h = -15.1586

[[price]]
pair = ["eth", "USD"]
value = 3888.42
market_cap = 441333339130.0
price_change_percentage_24h = -7.13881
market_cap_change_percentage_24h = -8.91262

[[price]]
pair = ["xrp", "USD"]
value = 1.3
market_cap = 58878506304.0
price_change_percentage_24h = -13.68192
market_cap_change_percentage_24h = -15.49979

[[price]]
pair = ["usdt", "USD"]
value = 0.977423
market_cap = 56629810887.0
price_change_percentage_24h = -2.44618
market_cap_change_percentage_24h = -1.6565

[[price]]
pair = ["ada", "USD"]
value = 1.63
market_cap = 49678601265.0
price_change_percentage_24h = -8.27028
market_cap_change_percentage_24h = -12.23593

[[price]]
pair = ["dot", "USD"]
value = 36.31
market_cap = 35131356791.0
price_change_percentage_24h = -6.27047
market_cap_change_percentage_24h = -8.63168

[[price]]
pair = ["ltc", "USD"]
value = 320.8
market_cap = 20831982599.0
price_change_percentage_24h = -16.81166
market_cap_change_percentage_24h = -18.70467

[[price]]
pair = ["uni", "USD"]
value = 37.37
market_cap = 18985593906.0
price_change_percentage_24h = -3.62782
market_cap_change_percentage_24h = -5.5185

[[price]]
pair = ["link", "USD"]
value = 42.54
market_cap = 17609789275.0
price_change_percentage_24h = -13.77443
market_cap_change_percentage_24h = -15.77539

[[price]]
pair = ["usdc", "USD"]
value = 1.01
market_cap = 15720219307.0
price_change_percentage_24h = 1.0737
market_cap_change_percentage_24h = -0.5122

[[price]]
pair = ["xlm", "USD"]
value = 0.584462
market_cap = 13256373982.0
price_change_percentage_24h = -19.47344
market_cap_change_percentage_24h = -21.3135

[[price]]
pair = ["sol", "USD"]
value = 43.63
market_cap = 11614588482.0
price_change_percentage_24h = -3.6873
market_cap_change_percentage_24h = -5.39863

[[price]]
pair = ["vet", "USD"]
value = 0.178647
market_cap = 11086838925.0
price_change_percentage_24h = -16.1892
market_cap_change_percentage_24h = -20.03487

[[price]]
pair = ["eos", "USD"]
value = 10.6
market_cap = 9800937463.0
price_change_percentage_24h = -25.62547
market_cap_change_percentage_24h = -30.15252

[[price]]
pair = ["theta", "USD"]
value = 9.39
market_cap = 9223580492.0
price_change_percentage_24h = -13.3496
market_cap_change_percentage_24h = -14.64239

[[price]]
pair = ["xmr", "USD"]
value = 394.77
market_cap = 7069662684.0
price_change_percentage_24h = -13.64045
market_cap_change_percentage_24h = -13.63704

[[price]]
pair = ["neo", "USD"]
value = 97.41
market_cap = 6870651015.0
price_change_percentage_24h = -15.13917
market_cap_change_percentage_24h = -15.13917

[[price]]
pair = ["aave", "USD"]
value = 513.07
market_cap = 6354933517.0
price_change_percentage_24h = 11.24791
market_cap_change_percentage_24h = 8.20749

[[price]]
pair = ["atom", "USD"]
value = 23.65
market_cap = 5411051362.0
price_change_percentage_24h = -12.18297
market_cap_change_percentage_24h = -15.67342

[[price]]
pair = ["miota", "USD"]
value = 1.77
market_cap = 4842251510.0
price_change_percentage_24h = -16.76324
market_cap_change_percentage_24h = -17.45056

[[price]]
pair = ["dai", "USD"]
value = 0.977931
market_cap = 4538029503.0
price_change_percentage_24h = -2.47351
market_cap_change_percentage_24h = -1.54966

[[price]]
pair = ["AVAX", "USD"]
value = 34.72
market_cap = 4399360258.0
price_change_percentage_24h = -7.04032
market_cap_change_percentage_24h = -8.05417

[[price]]
pair = ["ksm", "USD"]
value = 482.19
market_cap = 4242266368.0
price_change_percentage_24h = 10.08598
market_cap_change_percentage_24h = 7.33843

[[price]]
pair = ["comp", "USD"]
value = 755.56
market_cap = 3800547629.0
price_change_percentage_24h = -13.40832
market_cap_change_percentage_24h = -14.61092

[[price]]
pair = ["algo", "USD"]
value = 1.31
market_cap = 3768171376.0
price_change_percentage_24h = -11.66326
market_cap_change_percentage_24h = -15.95861

[[price]]
pair = ["zec", "USD"]
value = 298.56
market_cap = 3135038511.0
price_change_percentage_24h = -4.00541
market_cap_change_percentage_24h = -6.96072

[[price]]
pair = ["sushi", "USD"]
value = 15.65
market_cap = 2558065362.0
price_change_percentage_24h = 1.85814
market_cap_change_percentage_24h = -0.38

[[price]]
pair = ["bat", "USD"]
value = 1.19
market_cap = 1741867394.0
price_change_percentage_24h = -15.17729
market_cap_change_percentage_24h = -16.46472

[[price]]
pair = ["grt", "USD"]
value = 1.31
market_cap = 1577716447.0
price_change_percentage_24h = -11.68014
market_cap_change_percentage_24h = -12.9029

[[price]]
pair = ["uma", "USD"]
value = 25.91
market_cap = 1564317864.0
price_change_percentage_24h = -10.47295
market_cap_change_percentage_24h = -10.45602

[[price]]
pair = ["nano", "USD"]
value = 11.24
market_cap = 1409749329.0
price_change_percentage_24h = 26.24392
market_cap_change_percentage_24h = 18.60749

[[price]]
pair = ["icx", "USD"]
value = 2.08
market_cap = 1278573517.0
price_change_percentage_24h = -17.13815
market_cap_change_percentage_24h = -17.8943

[[price]]
pair = ["one", "USD"]
value = 0.109994
market_cap = 1044465414.0
price_change_percentage_24h = -10.93717
market_cap_change_percentage_24h = -11.04735

[[price]]
pair = ["xsushi", "USD"]
value = 16.48
market_cap = 934247639.0
price_change_percentage_24h = 12.29842
market_cap_change_percentage_24h = -4.38089

[[price]]
pair = ["ocean", "USD"]
value = 1.2
market_cap = 513318974.0
price_change_percentage_24h = -15.56413
market_cap_change_percentage_24h = -15.52664

[[price]]
pair = ["ewt", "USD"]
value = 15.36
market_cap = 503715952.0
price_change_percentage_24h = 9.6652
market_cap_change_percentage_24h = 5.6178

[[price]]
pair = ["celo", "USD"]
value = 4.45
market_cap = 490668592.0
price_change_percentage_24h = -14.20979
market_cap_change_percentage_24h = -14.57521

[[price]]
pair = ["reef", "USD"]
value = 0.04063622
market_cap = 487642462.0
price_change_percentage_24h = -18.8905
market_cap_change_percentage_24h = -24.59751

[[price]]
pair = ["nmr", "USD"]
value = 56.98
market_cap = 322184836.0
price_change_percentage_24h = -12.60829
market_cap_change_percentage_24h = -13.03724

[[price]]
pair = ["powr", "USD"]
value = 0.472023
market_cap = 202834431.0
price_change_percentage_24h = 14.84705
market_cap_change_percentage_24h = 14.88103

[[price]]
pair = ["dag", "USD"]
value = 0.080493
market_cap = 194620647.0
price_change_percentage_24h = -7.1619
market_cap_change_percentage_24h = -5.37987

[[price]]
pair = ["pols", "USD"]
value = 2.77
market_cap = 184326461.0
price_change_percentage_24h = -9.59616
market_cap_change_percentage_24h = -10.3063

[[price]]
pair = ["trac", "USD"]
value = 0.523977
market_cap = 183274553.0
price_change_percentage_24h = -12.29135
market_cap_change_percentage_24h = -15.22905

[[price]]
pair = ["nu", "USD"]
value = 0.404256
market_cap = 138734492.0
price_change_percentage_24h = -11.85532
market_cap_change_percentage_24h = -13.68116

[[price]]
pair = ["sylo", "USD"]
value = 0.01091777
market_cap = 26764423.0
price_change_percentage_24h = -19.09752
market_cap_change_percentage_24h = -22.29087

[[price]]
pair = ["gs", "USD"]
value = 1.15
market_cap = 0.0
price_change_percentage_24h = -11.61581
market_cap_change_percentage_24h = 0.0

[[price]]
pair = ["icp", "USD"]
value = 270.34
market_cap = 0.0
price_change_percentage_24h = -28.94635
market_cap_change_percentage_24h = 0.0

[[price]]
pair = ["icp", "USD"]
value = 271.38
market_cap = 0.0
price_change_percentage_24h = -27.13373
market_cap_change_percentage_24h = 0.0
