[[wallet]]
id = "blockfi"
name = "BlockFI"
url = "https://www.blockfi.com"

[[wallet.currency]]
symbol = "btc"
apy = 0.05
yield_type = "interest"

[[wallet.currency]]
symbol = "ltc"
apy = 0.055
yield_type = "interest"

[[wallet.currency]]
symbol = "eth"
apy = 0.045
yield_type = "interest"

[[wallet.currency]]
symbol = "usdc"
apy = 0.086
yield_type = "interest"

[[wallet.currency]]
symbol = "link"
apy = 0.045
yield_type = "interest"

[[wallet]]
id = "kraken"
name = "Kraken"
url = "https://www.kraken.com"

[[wallet.currency]]
symbol = "eth"
apy = 0.06
yield_type = "staking"

[[wallet.currency]]
symbol = "dot"
apy = 0.12
yield_type = "staking"

[[wallet.currency]]
symbol = "ksm"
apy = 0.12
yield_type = "staking"

[[wallet.currency]]
symbol = "atom"
apy = 0.07
yield_type = "staking"

[[wallet]]
id = "nexo"
name = "Nexo"
url = "https://www.nexo.io"

[[wallet.currency]]
symbol = "xlm"
apy = 0.05
yield_type = "interest"

[[wallet.currency]]
symbol = "eos"
apy = 0.05
yield_type = "interest"

[[wallet]]
id = "yoroi"
name = "Yoroi"
url = "https://yoroi-wallet.com/"

[[wallet.currency]]
symbol = "ada"
apy = 0.04
yield_type = "staking"

[[wallet]]
id = "valora"
name = "Valora"
url = "https://valoraapp.com"

[[wallet.currency]]
symbol = "celo"
apy = 0.1323
yield_type = "staking"

[[wallet]]
id = "coinbase"
name = "Coinbase"
url = "https://www.coinbase.com"

[[wallet.currency]]
symbol = "algo"
apy = 0.06
yield_type = "staking"

[[wallet]]
id = "metamask"
name = "MetaMask"
url = "https://www.metamask.com"

[[wallet.currency]]
symbol = "pols"
apy = 0.10
yield_type = "lp"

[[wallet.currency]]
symbol = "eth"
apy = 0.10
yield_type = "lp"

[[wallet.currency]]
symbol = "usdc"
apy = 0.03
yield_type = "interest"

[[wallet.currency]]
symbol = "dai"
apy = 0.223
yield_type = "interest"

[[wallet.currency]]
symbol = "xsushi"
apy = 0.11
yield_type = "interest"

[[wallet]]
id = "gemini"
name = "Gemini"
url = "https://www.gemini.com"

[[wallet.currency]]
symbol = "comp"
apy = 0.0247
yield_type = "interest"

[[wallet.currency]]
symbol = "aave"
apy = 0.0583
yield_type = "interest"

[[wallet.currency]]
symbol = "bat"
apy = 0.0349
yield_type = "interest"

[[wallet.currency]]
symbol = "zec"
apy = 0.0175
yield_type = "interest"

[[wallet.currency]]
symbol = "grt"
apy = 0.0126
yield_type = "interest"

[[wallet.currency]]
symbol = "uni"
apy = 0.0359
yield_type = "interest"

[[wallet]]
id = "pool-x"
name = "Pool X"
url = "https://www.pool-x.com"

[[wallet.currency]]
symbol = "one"
apy = 0.08
yield_type = "staking"

[[wallet]]
id = "myalgo"
name = "My Algo"
url = "https://wallet.myalgo.com/"

[[wallet.currency]]
symbol = "algo"
apy = 0.0564
yield_type = "staking"

[[wallet]]
id = "solflare"
name = "SolFlare"
url = "https://www.solflare.com"

[[wallet.currency]]
symbol = "sol"
apy = 0.102
yield_type = "staking"
