[[wallet]]
id = "blockfi"
name = "BlockFI"
url = "https://www.blockfi.com"

[[wallet.currency]]
symbol = "btc"
apy = 0.06
yield_type = "interest"

[[wallet.currency]]
symbol = "ltc"
apy = 0.065
yield_type = "interest"

[[wallet.currency]]
symbol = "eth"
apy = 0.05
yield_type = "interest"

[[wallet]]
id = "kraken"
name = "Kraken"
url = "https://www.kraken.com"

[[wallet.currency]]
symbol = "eth"
apy = 0.07
yield_type = "staking"
