CREATE TABLE IF NOT EXISTS markets (
  id VARCHAR NOT NULL PRIMARY KEY,
  name VARCHAR  NOT NULL
);

CREATE TABLE IF NOT EXISTS market_coins (
  market VARCHAR NOT NULL,
  coin VARCHAR NOT NULL,
  PRIMARY KEY (market, coin),
  FOREIGN KEY (market) REFERENCES markets (id) ON DELETE CASCADE,
  FOREIGN KEY (coin) REFERENCES coins (id) ON DELETE CASCADE
);
