CREATE TABLE IF NOT EXISTS markets (
  id VARCHAR NOT NULL PRIMARY KEY,
  name VARCHAR  NOT NULL
);

CREATE TABLE IF NOT EXISTS market_assets (
  market VARCHAR NOT NULL,
  asset VARCHAR NOT NULL,
  class VARCHAR NOT NULL,
  PRIMARY KEY (market, asset, class),
  FOREIGN KEY (market) REFERENCES markets (id) ON DELETE CASCADE,
  FOREIGN KEY (asset, class) REFERENCES assets (id, class) ON DELETE CASCADE
);
